FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/api/package.json apps/api/package.json
COPY services/metrics-lambda services/metrics-lambda
RUN npm install --omit=dev
COPY apps/api apps/api
WORKDIR /app/apps/api
EXPOSE 3001
CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && node prisma/seed.js && npm start"]
