import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:3001';
const request = async (path, options = {}, token) => {
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  if (!response.ok) throw new Error((await response.json()).message || 'Ha ocurrido un error');
  return response.status === 204 ? null : response.json();
};
function Login({ onLogin }) {
  const [email, setEmail] = useState('admin@demo.local'); const [password, setPassword] = useState('Admin123!'); const [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); try { const result = await request('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); onLogin(result); } catch (e) { setError(e.message); } }
  return <main className="login"><section><p className="eyebrow">TEAM NOTES</p><h1>Trabajo visible,<br />equipo alineado.</h1><p>Accede al tablero compartido y mantén el pulso de tu actividad.</p></section><form onSubmit={submit}><h2>Iniciar sesión</h2><label>Correo<input value={email} onChange={e => setEmail(e.target.value)} type="email" /></label><label>Contraseña<input value={password} onChange={e => setPassword(e.target.value)} type="password" /></label>{error && <p className="error">{error}</p>}<button>Entrar</button><small>Demo admin: admin@demo.local / Admin123!</small><small>Demo usuario: usuario@demo.local / User123!</small></form></main>;
}
function Note({ note, token, refresh }) {
  const [draft, setDraft] = useState(note); const [editing, setEditing] = useState(false);
  useEffect(() => setDraft(note), [note]);
  const save = async () => { await request(`/notes/${note.id}`, { method: 'PUT', body: JSON.stringify(draft) }, token); setEditing(false); refresh(); };
  const dragEnd = async (e) => { const board = e.currentTarget.parentElement.getBoundingClientRect(); await request(`/notes/${note.id}/position`, { method: 'PATCH', body: JSON.stringify({ x: Math.max(0, e.clientX - board.left - 130), y: Math.max(0, e.clientY - board.top - 80) }) }, token); refresh(); };
  return <article draggable onDragEnd={dragEnd} className={`note ${draft.status.toLowerCase().replace(' ', '-')}`} style={{ left: note.x, top: note.y }}>
    {editing ? <><input value={draft.title} placeholder="Título de la nota" aria-label="Título de la nota" onChange={e => setDraft({...draft,title:e.target.value})}/><textarea value={draft.text} placeholder="Describe la tarea..." aria-label="Texto de la nota" onChange={e => setDraft({...draft,text:e.target.value})}/><select value={draft.status} onChange={e => setDraft({...draft,status:e.target.value})}><option>Pendiente</option><option>En curso</option><option>Hecho</option></select><button onClick={save}>Guardar</button></> : <><div className="note-head"><span>{note.status}</span><button className="icon" onClick={() => request(`/notes/${note.id}`, {method:'DELETE'}, token).then(refresh)}>×</button></div><h3>{note.title || 'Sin título'}</h3><p>{note.text || 'Sin descripción'}</p><button className="link" onClick={() => setEditing(true)}>Editar</button></>}
  </article>;
}
function App() {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem('session') || 'null')); const [page, setPage] = useState('board'); const [notes, setNotes] = useState([]); const [metrics, setMetrics] = useState(null); const [users, setUsers] = useState([]);
  const refresh = async () => { if (!session) return; setNotes(await request('/notes', {}, session.token)); if (page === 'dashboard') setMetrics(await request('/dashboard/metrics', {}, session.token)); if (page === 'users') setUsers(await request('/users', {}, session.token)); };
  useEffect(() => { refresh().catch(console.error); }, [session, page]);
  if (!session) return <Login onLogin={s => { localStorage.setItem('session', JSON.stringify(s)); setSession(s); }} />;
  const addNote = () => request('/notes', {method:'POST', body: JSON.stringify({title:'',text:'',status:'Pendiente',x:80,y:80})}, session.token).then(refresh);
  return <div className="app"><aside><div className="brand">TN</div><nav><button className={page==='board'?'active':''} onClick={() => setPage('board')}>Tablero</button><button className={page==='dashboard'?'active':''} onClick={() => setPage('dashboard')}>Dashboard</button>{session.user.role === 'ADMIN' && <button className={page==='users'?'active':''} onClick={() => setPage('users')}>Usuarios</button>}</nav><div className="profile"><strong>{session.user.name}</strong><span>{session.user.role === 'ADMIN' ? 'Administrador' : 'Usuario'}</span><button onClick={() => {localStorage.removeItem('session');setSession(null)}}>Salir</button></div></aside><main className="content">
    {page === 'board' && <><header><div><p className="eyebrow">ESPACIO COMPARTIDO</p><h1>Tablero de notas</h1></div><button onClick={addNote}>+ Nueva nota</button></header><section className="board">{notes.map(n => <Note key={n.id} note={n} token={session.token} refresh={refresh}/>)}</section></>}
    {page === 'dashboard' && <><header><div><p className="eyebrow">RESUMEN</p><h1>Dashboard</h1></div></header>{metrics && <section className="metrics"><div><span>Total</span><b>{metrics.total}</b></div>{Object.entries(metrics.byStatus).map(([key,value]) => <div key={key}><span>{key}</span><b>{value}</b></div>)}</section>}</>}
    {page === 'users' && <Users users={users} token={session.token} refresh={refresh}/>}</main></div>;
}
function Users({users,token,refresh}) { const [form,setForm]=useState({name:'',email:'',password:'',role:'USER'}); const [editingId,setEditingId]=useState(null); const [draft,setDraft]=useState(null); const [error,setError]=useState(''); const submit=async e=>{e.preventDefault();try{await request('/users',{method:'POST',body:JSON.stringify(form)},token);setForm({name:'',email:'',password:'',role:'USER'});setError('');refresh()}catch(e){setError(e.message)}}; const startEdit=u=>{setEditingId(u.id);setDraft({name:u.name,email:u.email,role:u.role})}; const saveEdit=async()=>{try{await request(`/users/${editingId}`,{method:'PATCH',body:JSON.stringify(draft)},token);setEditingId(null);setDraft(null);setError('');refresh()}catch(e){setError(e.message)}}; return <><header><div><p className="eyebrow">ADMINISTRACIÓN</p><h1>Usuarios</h1></div></header><section className="users">{error&&<p className="error">{error}</p>}<form onSubmit={submit}><input placeholder="Nombre" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Correo" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Contraseña" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="USER">Usuario</option><option value="ADMIN">Administrador</option></select><button>Crear usuario</button></form>{users.map(u=>editingId===u.id?<article className="user" key={u.id}><div className="user-form"><input value={draft.name} aria-label="Nombre" onChange={e=>setDraft({...draft,name:e.target.value})}/><input value={draft.email} aria-label="Correo" onChange={e=>setDraft({...draft,email:e.target.value})}/><select value={draft.role} aria-label="Rol" onChange={e=>setDraft({...draft,role:e.target.value})}><option value="USER">Usuario</option><option value="ADMIN">Administrador</option></select></div><div className="user-actions"><button onClick={saveEdit}>Guardar</button><button onClick={()=>{setEditingId(null);setDraft(null)}}>Cancelar</button></div></article>:<article className="user" key={u.id}><div><b>{u.name}</b><span>{u.email} · {u.role}</span></div><div className="user-actions"><button onClick={()=>startEdit(u)}>Editar</button><button onClick={()=>request(`/users/${u.id}/status`,{method:'PATCH',body:JSON.stringify({active:!u.active})},token).then(refresh)}>{u.active?'Desactivar':'Reactivar'}</button><button className="danger" onClick={()=>window.confirm(`¿Eliminar a ${u.name}?`) && request(`/users/${u.id}`,{method:'DELETE'},token).then(refresh)}>Eliminar</button></div></article>)}</section></> }
createRoot(document.getElementById('root')).render(<App/>);
